*** Variables ***
${MAIN_SV}        https://simanqa.myvtex.com/admin
${MAIN_GT}        https://simanqagt.myvtex.com/admin
${MAIN_CR}        https://simanqacr.myvtex.com/admin
${MAIN_NI}        https://simanqani.myvtex.com/admin
${INSTORE_SV}     https://simanqainstoresv.myvtex.com/admin
${INSTORE_GT}     https://simanqainstoregt.myvtex.com/admin
${INSTORE_CR}     https://simanqainstorecr.myvtex.com/admin
${INSTORE_NI}     https://simanqainstorni.myvtex.com/admin